name: "Publish on GitHub Pages"

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "ubuntu-22.04"
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1

      - name: "Set up Hugo"
        uses: "peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d" # renovate: tag=v2.6.0
        with:
          hugo-version: "0.111.3"
          extended: true

      - name: "Set up Node.js"
        uses: "actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8" # v4.0.2
        with:
          node-version: 18

      - name: "Install npm dependencies"
        run: "npm ci"

      - name: "Format codes"
        run: "npm run format"

      - name: "Build"
        run: "npm run build"

      - name: "Deploy"
        uses: "peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e" # v4.0.0
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: "./public"
          cname: "digicre.net"
